name: pragmabackend
services:
  backend-pgdb:
    build:
      context: .
      dockerfile: ./Postgres.dockerfile
    image: pragmabackend-pgdb:latest
    container_name: pragmabackend-pgdb
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: pragmabackend
    volumes:
      - pragmabackend_data:/var/lib/postgresql
    ports:
      - "1264:5432"
    networks:
      - pragmabackend_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pragmabackend"]
      interval: 3s
      timeout: 3s
      retries: 10
  backend:
    build:
      context: ..
      dockerfile: ./Backend.dockerfile
    image: pragmabackend:latest
    container_name: pragmabackend
    restart: unless-stopped
    depends_on:
      backend-pgdb:
        condition: service_healthy
    ports:
      - "21330:21330"
      - "21331:21331"
      - "21332:21332"
    healthcheck:
      test: ["CMD", "curl", "-fs", "http://localhost:21330/instance-healthcheck"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_interval: 2s
      start_period: 60s
    networks:
      - pragmabackend_net
    volumes:
      - ../BackendServer/resources/docker.env.json:/app/resources/env.json:ro
volumes:
  pragmabackend_data:
networks:
  pragmabackend_net:
    driver: bridge
