CREATE TABLE IF NOT EXISTS match_history_player_data (
	match_id UUID NOT NULL,
	team_number INT NOT NULL,
	player_id UUID NOT NULL,
	native_platform_id TEXT NOT NULL,
	saved_player_name TEXT NOT NULL,
	selected_banner_catalog_id TEXT NOT NULL,
	saved_sponsor_name TEXT NOT NULL,
	sponsor_game_id TEXT NOT NULL,
	is_anonymous_player BOOL NOT NULL,
	has_crew_score_earned BOOL NOT NULL,
	teammate_index INT NOT NULL,
	num_kills INT NOT NULL,
	num_assists INT NOT NULL,
	num_deaths INT NOT NULL,
	total_damage INT NOT NULL,
	current_rank_id INT NOT NULL,
	previous_rank_id INT NOT NULL,
	current_ranked_rating INT NOT NULL,
	previous_ranked_rating INT NOT NULL,
	ranked_rating_delta INT NOT NULL,
	crew_id UUID NOT NULL,
	division_id UUID NOT NULL,
	division_type INT NOT NULL,
	match_placement_data TEXT[] NOT NULL,
	num_ranked_matches INT NOT NULL,
	PRIMARY KEY (match_id, team_number, player_id)
);