INSERT INTO profile_data (
	player_id,
	display_name,
	banner_item_id,
	pre_spray_item_id,
	match_spray_item_id,
	post_spray_item_id,
	attacker_outfit_loadout_id,
	defender_outfit_loadout_id,
	attacker_weapon_loadout_id,
	defender_weapon_loadout_id,
	last_updated,
	next_new_day_rollover,
	last_login,
	player_flags,
	crew_score,
	current_solo_rank,
	highest_team_rank,
	division_type,
	inventory_version,
	crew_id,
	account_id_provider,
	platform_name,
	provider_account_id,
	crossplay_platform_kind,
	games_remaining_until_crew_join
) VALUES (
	@player_id,
	@display_name,
	@banner_item_id,
	@pre_spray_item_id,
	@match_spray_item_id,
	@post_spray_item_id,
	@attacker_outfit_loadout_id,
	@defender_outfit_loadout_id,
	@attacker_weapon_loadout_id,
	@defender_weapon_loadout_id,
	@last_updated,
	@next_new_day_rollover,
	@last_login,
	@player_flags,
	@crew_score,
	@current_solo_rank,
	@highest_team_rank,
	@division_type,
	@inventory_version,
	@crew_id,
	@account_id_provider,
	@platform_name,
	@provider_account_id,
	@crossplay_platform_kind,
	@games_remaining_until_crew_join
) ON CONFLICT (player_id)
DO UPDATE SET
	display_name = EXCLUDED.display_name,
	banner_item_id = EXCLUDED.banner_item_id,
	pre_spray_item_id = EXCLUDED.pre_spray_item_id,
	match_spray_item_id = EXCLUDED.match_spray_item_id,
	post_spray_item_id = EXCLUDED.post_spray_item_id,
	attacker_outfit_loadout_id = EXCLUDED.attacker_outfit_loadout_id,
	defender_outfit_loadout_id = EXCLUDED.defender_outfit_loadout_id,
	attacker_weapon_loadout_id = EXCLUDED.attacker_weapon_loadout_id,
	defender_weapon_loadout_id = EXCLUDED.defender_weapon_loadout_id,
	last_updated = EXCLUDED.last_updated,
	next_new_day_rollover = EXCLUDED.next_new_day_rollover,
	last_login = EXCLUDED.last_login,
	player_flags = EXCLUDED.player_flags,
	crew_score = EXCLUDED.crew_score,
	current_solo_rank = EXCLUDED.current_solo_rank,
	highest_team_rank = EXCLUDED.highest_team_rank,
	division_type = EXCLUDED.division_type,
	inventory_version = EXCLUDED.inventory_version,
	crew_id = EXCLUDED.crew_id,
	account_id_provider = EXCLUDED.account_id_provider,
	platform_name = EXCLUDED.platform_name,
	provider_account_id = EXCLUDED.provider_account_id,
	crossplay_platform_kind = EXCLUDED.crossplay_platform_kind,
	games_remaining_until_crew_join = EXCLUDED.games_remaining_until_crew_join;