INSERT INTO legacystats_ranked (
	player_id,
	kill_count,
	death_count,
	ace_count,
	duality_kill_count,
	first_kill_count,
	first_death_count,
	kast,
	duality_rating,
	impact_count,
	total_matches_played,
	fan_count,
	win_count,
	total_rounds_played,
	headshots_count,
	total_damaging_shots_count,
	total_damage,
	top_sponsors,
	top_weapons
) VALUES (
	@player_id,
	@kill_count,
	@death_count,
	@ace_count,
	@duality_kill_count,
	@first_kill_count,
	@first_death_count,
	@kast,
	@duality_rating,
	@impact_count,
	@total_matches_played,
	@fan_count,
	@win_count,
	@total_rounds_played,
	@headshots_count,
	@total_damaging_shots_count,
	@total_damage,
	@top_sponsors,
	@top_weapons
) ON CONFLICT (player_id)
DO UPDATE SET
	kill_count = EXCLUDED.kill_count,
	death_count = EXCLUDED.death_count,
	ace_count = EXCLUDED.ace_count,
	duality_kill_count = EXCLUDED.duality_kill_count,
	first_kill_count = EXCLUDED.first_kill_count,
	first_death_count = EXCLUDED.first_death_count,
	kast = EXCLUDED.kast,
	duality_rating = EXCLUDED.duality_rating,
	impact_count = EXCLUDED.impact_count,
	total_matches_played = EXCLUDED.total_matches_played,
	fan_count = EXCLUDED.fan_count,
	win_count = EXCLUDED.win_count,
	total_rounds_played = EXCLUDED.total_rounds_played,
	headshots_count = EXCLUDED.headshots_count,
	total_damaging_shots_count = EXCLUDED.total_damaging_shots_count,
	total_damage = EXCLUDED.total_damage,
	top_sponsors = EXCLUDED.top_sponsors,
	top_weapons = EXCLUDED.top_weapons;