INSERT INTO weapon_loadouts (
	loadout_id,
	player_id,
	semi_auto_pistol,
	suppressed_pistol,
	auto_pistol,
	highcal_pistol,
	heavy_shotgun,
	auto_shotgun,
	tactical_smg,
	rapidfire_smg,
	suppressed_smg,
	standard_ar,
	semi_auto_ar,
	burst_ar,
	tactical_ar,
	suppressed_ar,
	heavy_ar,
	highcal_mg,
	rapidfire_mg,
	semi_auto_sniper,
	bolt_action_sniper,
	melee
) VALUES (
	@loadout_id,
	@player_id,
	@semi_auto_pistol,
	@suppressed_pistol,
	@auto_pistol,
	@highcal_pistol,
	@heavy_shotgun,
	@auto_shotgun,
	@tactical_smg,
	@rapidfire_smg,
	@suppressed_smg,
	@standard_ar,
	@semi_auto_ar,
	@burst_ar,
	@tactical_ar,
	@suppressed_ar,
	@heavy_ar,
	@highcal_mg,
	@rapidfire_mg,
	@semi_auto_sniper,
	@bolt_action_sniper,
	@melee
) ON CONFLICT (loadout_id)
DO UPDATE SET
	player_id = EXCLUDED.player_id,
	semi_auto_pistol = EXCLUDED.semi_auto_pistol,
	suppressed_pistol = EXCLUDED.suppressed_pistol,
	auto_pistol = EXCLUDED.auto_pistol,
	highcal_pistol = EXCLUDED.highcal_pistol,
	heavy_shotgun = EXCLUDED.heavy_shotgun,
	auto_shotgun = EXCLUDED.auto_shotgun,
	tactical_smg = EXCLUDED.tactical_smg,
	rapidfire_smg = EXCLUDED.rapidfire_smg,
	suppressed_smg = EXCLUDED.suppressed_smg,
	standard_ar = EXCLUDED.standard_ar,
	semi_auto_ar = EXCLUDED.semi_auto_ar,
	burst_ar = EXCLUDED.burst_ar,
	tactical_ar = EXCLUDED.tactical_ar,
	suppressed_ar = EXCLUDED.suppressed_ar,
	heavy_ar = EXCLUDED.heavy_ar,
	highcal_mg = EXCLUDED.highcal_mg,
	rapidfire_mg = EXCLUDED.rapidfire_mg,
	semi_auto_sniper = EXCLUDED.semi_auto_sniper,
	bolt_action_sniper = EXCLUDED.bolt_action_sniper,
	melee = EXCLUDED.melee;