ALTER TABLE parties ADD COLUMN IF NOT EXISTS party_ext_version TEXT NOT NULL DEFAULT '173322';
ALTER TABLE parties ADD COLUMN IF NOT EXISTS region TEXT NOT NULL DEFAULT '';
ALTER TABLE parties ADD COLUMN IF NOT EXISTS tag TEXT NOT NULL DEFAULT '';
ALTER TABLE parties ADD COLUMN IF NOT EXISTS profile TEXT NOT NULL DEFAULT '';
ALTER TABLE parties ADD COLUMN IF NOT EXISTS has_acceptable_region BOOL NOT NULL DEFAULT TRUE;
ALTER TABLE parties ADD COLUMN IF NOT EXISTS preferred_game_server_zones TEXT[] NOT NULL DEFAULT ARRAY['uscentral-1']::TEXT[];
ALTER TABLE parties ADD COLUMN IF NOT EXISTS standard HSTORE NOT NULL DEFAULT hstore('mode', 'Standard');
ALTER TABLE parties ADD COLUMN IF NOT EXISTS custom_json TEXT NOT NULL DEFAULT '';
ALTER TABLE parties ADD COLUMN IF NOT EXISTS crossplay_platform TEXT NOT NULL DEFAULT 'CROSS_PLAY_PLATFORM_PC';