COPY profile_data (
player_id,
display_name,
banner_item_id,
pre_spray_item_id,
match_spray_item_id,
post_spray_item_id,
attacker_outfit_loadout_id,
defender_outfit_loadout_id,
attacker_weapon_loadout_id,
defender_weapon_loadout_id,
last_updated,
next_new_day_rollover,
last_login,
player_flags,
crew_score,
current_solo_rank,
highest_team_rank,
division_type,
inventory_version,
crew_id,
account_id_provider,
platform_name,
provider_account_id,
crossplay_platform_kind,
games_remaining_until_crew_join
) FROM STDIN (FORMAT BINARY);