COPY weapon_loadouts (
loadout_id,
player_id,
semi_auto_pistol,
suppressed_pistol,
auto_pistol,
highcal_pistol,
heavy_shotgun,
auto_shotgun,
tactical_smg,
rapidfire_smg,
suppressed_smg,
standard_ar,
semi_auto_ar,
burst_ar,
tactical_ar,
suppressed_ar,
heavy_ar,
highcal_mg,
rapidfire_mg,
semi_auto_sniper,
bolt_action_sniper,
melee
) FROM STDIN (FORMAT BINARY);