CREATE TABLE IF NOT EXISTS player_config (
    player_id UUID PRIMARY KEY,
    unlock_all_play_modes BOOL NOT NULL,
    unlock_all_menu_tabs BOOL NOT NULL,
    unlock_all_sponsors BOOL NOT NULL,
    bypass_unlock_all_sponsors_override BOOL NOT NULL,
    bypass_progression_overrides BOOL NOT NULL,
    bypass_team_size_overrides BOOL NOT NULL,
    bypass_region_select_override BOOL NOT NULL,
    bypass_currency_purchasing_override BOOL NOT NULL,
    disable_dev_map_selector BOOL NOT NULL,
    show_debug_info_panel BOOL NOT NULL,
    show_platform_info_panel BOOL NOT NULL,
    show_matchmaking_counters BOOL NOT NULL,
    force_chat_enabled BOOL NOT NULL,
    most_recent_lobby_mode INT NOT NULL,
    most_recent_party_id TEXT NOT NULL,
    eula_accepted_version INT NOT NULL,
    eula_accepted_version_playstation INT NOT NULL,
    eula_accepted_version_xbox INT NOT NULL,
    tos_accepted_version INT NOT NULL,
    tos_accepted_version_playstation INT NOT NULL,
    tos_accepted_version_xbox INT NOT NULL,
    nda_accepted_version INT NOT NULL,
    nda_accepted_version_playstation INT NOT NULL,
    nda_accepted_version_xbox INT NOT NULL,
    seizure_warning_ack_version INT NOT NULL,
    seizure_warning_ack_version_playstation INT NOT NULL,
    seizure_warning_ack_version_xbox INT NOT NULL,
    battlepass_season_logged_on INT NOT NULL,
    battlepass_purchase_popup_last_time DOUBLE PRECISION NOT NULL,
    nda_signature TEXT NOT NULL,
    nda_signature_playstation TEXT NOT NULL,
    nda_signature_xbox TEXT NOT NULL,
    nda_email TEXT NOT NULL,
    nda_email_playstation TEXT NOT NULL,
    nda_email_xbox TEXT NOT NULL,
    last_version_shown_in_drivers_warning TEXT NOT NULL,
    min_spec_warning_times_displayed INT NOT NULL,
    ping_warning_dialog_times_displayed INT NOT NULL,
    completed_launch_settings_flow BOOL NOT NULL,
    using_manual_matchmaking_region_selection BOOL NOT NULL,
    manual_matchmaking_region_selections TEXT [] NOT NULL,
    rotating_news_viewed_messages TEXT [] NOT NULL,
    ink_quality DOUBLE PRECISION NOT NULL,
    mouse_sensitivity_ads_scale DOUBLE PRECISION NOT NULL,
    minimap_scale DOUBLE PRECISION NOT NULL,
    minimap_size DOUBLE PRECISION NOT NULL,
    minimap_mask_opacity DOUBLE PRECISION NOT NULL,
    inverted_y_axis BOOL NOT NULL,
    toggle_crouch BOOL NOT NULL,
    toggle_walk BOOL NOT NULL,
    toggle_ads BOOL NOT NULL,
    recoil_behavior TEXT NOT NULL,
    left_handed_enabled BOOL NOT NULL,
    recoil_pitch_correction_enabled BOOL NOT NULL,
    is_team_laser_enabled BOOL NOT NULL,
    is_hud_minimap_rotation_enabled BOOL NOT NULL,
    is_hud_minimap_centered_on_player BOOL NOT NULL,
    is_hud_minimap_circle BOOL NOT NULL,
    is_hud_minimap_mask_high_contrast_enabled BOOL NOT NULL,
    is_hud_snap_minimap_with_scoreboard_enabled BOOL NOT NULL,
    is_damage_camera_effect_enabled BOOL NOT NULL,
    streamer_mode_enabled BOOL NOT NULL,
    hide_lobby_code BOOL NOT NULL,
    ads_tracer_ratio DOUBLE PRECISION NOT NULL,
    ads_tracer_intensity DOUBLE PRECISION NOT NULL,
    optic_hit_confirm_intensity DOUBLE PRECISION NOT NULL,
    anonymous_mode BOOL NOT NULL,
    anonymize_player_names BOOL NOT NULL,
    streamer_mode_disable_incoming_voice_chat BOOL NOT NULL,
    streamer_mode_disable_incoming_text_chat BOOL NOT NULL,
    is_text_chat_sound_effects_enabled BOOL NOT NULL,
    subtitles_enabled BOOL NOT NULL,
    verbose_vo_level TEXT NOT NULL,
    is_blood_fx_enabled BOOL NOT NULL,
    override_keymaps TEXT [] NOT NULL,
    voice_chat_input_audio_device TEXT NOT NULL,
    voice_chat_output_audio_device TEXT NOT NULL,
    voice_chat_team_enabled BOOL NOT NULL,
    voice_chat_console_mode TEXT NOT NULL,
    voice_chat_party_enabled BOOL NOT NULL,
    voice_chat_party_enabled_in_game BOOL NOT NULL,
    voice_chat_team_push_to_talk BOOL NOT NULL,
    voice_chat_party_push_to_talk BOOL NOT NULL,
    enabled_text_stats TEXT [] NOT NULL,
    enabled_graph_stats TEXT [] NOT NULL,
    muted_chat_contexts TEXT [] NOT NULL,
    input_bindings_version INT NOT NULL,
    player_config_version INT NOT NULL
);
