name: autoformat
on:
  pull_request:
  push:
    branches: [master]
jobs:
  clang-format:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}

      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format

      - name: Run clang-format
        run: |
          FILES=$(
            find . \( \
            -regex '\./\(Persistence\|Packets\|tests\)/Implementation/.*\.cpp' -o \
            -regex '\./\(Persistence\|Packets\|tests\)/Model/.*\.h' \
            \) \
            | grep -vE 'out/|vcpkg_installed/|vcpkg/'
            )
          
          clang-format -i $FILES main.cpp StaticHTTPPackets.cpp StaticWSPackets.cpp