INSERT INTO crosshair_config
(player_id,
color_index,
advanced_crosshair_settings,
custom_color,
fire_accuracy_fade,
follow_recoil,
show_outlines,
outline_thickness,
outline_opacity,
show_center_dot,
use_ads_settings,
center_dot,
center_dot_ads,
sniper_dot,
inner_pip,
outer_pip,
crosshair_config_version
) VALUES (
@player_id,
@color_index,
@advanced_crosshair_settings,
@custom_color,
@fire_accuracy_fade,
@follow_recoil,
@show_outlines,
@outline_thickness,
@outline_opacity,
@show_center_dot,
@use_ads_settings,
@center_dot,
@center_dot_ads,
@sniper_dot,
@inner_pip,
@outer_pip,
@version
) ON CONFLICT (player_id)
DO UPDATE SET
	color_index = EXCLUDED.color_index,
	custom_color = EXCLUDED.custom_color,
	advanced_crosshair_settings = EXCLUDED.advanced_crosshair_settings,
	fire_accuracy_fade = EXCLUDED.fire_accuracy_fade,
	follow_recoil = EXCLUDED.follow_recoil,
	show_outlines = EXCLUDED.show_outlines,
	outline_thickness = EXCLUDED.outline_thickness,
	outline_opacity = EXCLUDED.outline_opacity,
	show_center_dot = EXCLUDED.show_center_dot,
	use_ads_settings = EXCLUDED.use_ads_settings,
	center_dot = EXCLUDED.center_dot,
	center_dot_ads = EXCLUDED.center_dot_ads,
	sniper_dot = EXCLUDED.sniper_dot,
	inner_pip = EXCLUDED.inner_pip,
	outer_pip = EXCLUDED.outer_pip,
	crosshair_config_version = EXCLUDED.crosshair_config_version;