INSERT INTO gamepad_config (
	player_id,
	input_scheme_index,
	gamepad_glyph_index,
	look_preset_index,
	custom_look_config,
	custom_response_curve,
	invert_look,
	controller_feedback_value,
	turn_accel,
	aim_assist,
	response_curve_index,
	response_curve_arc_deg,
	response_curve_slope,
	response_curve_linear_blend_pow,
	custom_scale_ads,
	toggle_crouch,
	toggle_walk,
	toggle_plant_defuse,
	toggle_ads,
	end_walk_when_firing_behavior,
	ads_trigger_threshold,
	dead_zone_move_amount,
	custom_dead_zone_move_amount,
	dead_zone_look_amount,
	custom_dead_zone_look_amount,
	walk_run_deflection_threshold,
	gamepad_config_version
) VALUES (
	@player_id,
	@input_scheme_index,
	@gamepad_glyph_index,
	@look_preset_index,
	@custom_look_config,
	@custom_response_curve,
	@invert_look,
	@controller_feedback_value,
	@turn_accel,
	@aim_assist,
	@response_curve_index,
	@response_curve_arc_deg,
	@response_curve_slope,
	@response_curve_linear_blend_pow,
	@custom_scale_ads,
	@toggle_crouch,
	@toggle_walk,
	@toggle_plant_defuse,
	@toggle_ads,
	@end_walk_when_firing_behavior,
	@ads_trigger_threshold,
	@dead_zone_move_amount,
	@custom_dead_zone_move_amount,
	@dead_zone_look_amount,
	@custom_dead_zone_look_amount,
	@walk_run_deflection_threshold,
	@version
) ON CONFLICT (player_id)
DO UPDATE SET
	input_scheme_index = EXCLUDED.input_scheme_index,
	gamepad_glyph_index = EXCLUDED.gamepad_glyph_index,
	look_preset_index = EXCLUDED.look_preset_index,
	custom_look_config = EXCLUDED.custom_look_config,
	custom_response_curve = EXCLUDED.custom_response_curve,
	invert_look = EXCLUDED.invert_look,
	controller_feedback_value = EXCLUDED.controller_feedback_value,
	turn_accel = EXCLUDED.turn_accel,
	aim_assist = EXCLUDED.aim_assist,
	response_curve_index = EXCLUDED.response_curve_index,
	response_curve_arc_deg = EXCLUDED.response_curve_arc_deg,
	response_curve_slope = EXCLUDED.response_curve_slope,
	response_curve_linear_blend_pow = EXCLUDED.response_curve_linear_blend_pow,
	custom_scale_ads = EXCLUDED.custom_scale_ads,
	toggle_crouch = EXCLUDED.toggle_crouch,
	toggle_walk = EXCLUDED.toggle_walk,
	toggle_plant_defuse = EXCLUDED.toggle_plant_defuse,
	toggle_ads = EXCLUDED.toggle_ads,
	end_walk_when_firing_behavior = EXCLUDED.end_walk_when_firing_behavior,
	ads_trigger_threshold = EXCLUDED.ads_trigger_threshold,
	dead_zone_move_amount = EXCLUDED.dead_zone_move_amount,
	custom_dead_zone_move_amount = EXCLUDED.custom_dead_zone_move_amount,
	dead_zone_look_amount = EXCLUDED.dead_zone_look_amount,
	custom_dead_zone_look_amount = EXCLUDED.custom_dead_zone_look_amount,
	walk_run_deflection_threshold = EXCLUDED.walk_run_deflection_threshold,
	gamepad_config_version = EXCLUDED.gamepad_config_version;