INSERT INTO player_matchmaking_data (
	player_id,
	casual_mmr,
	ranked_mmr,
	solo_rank_points,
	casual_matches_played,
	ranked_matches_played,
	casual_matches_played_seasonal,
	ranked_matches_played_seasonal,
	ranked_placement_matches,
	current_solo_rank,
	highest_team_rank,
	casual_matches_won,
	ranked_matches_won,
	priority_matchmaking_until,
	restrict_matchmaking_until,
	map_history
) VALUES (
	@player_id,
	@casual_mmr,
	@ranked_mmr,
	@solo_rank_points,
	@casual_matches_played,
	@ranked_matches_played,
	@casual_matches_played_seasonal,
	@ranked_matches_played_seasonal,
	@ranked_placement_matches,
	@current_solo_rank,
	@highest_team_rank,
	@casual_matches_won,
	@ranked_matches_won,
	@priority_matchmaking_until,
	@restrict_matchmaking_until,
	@map_history
) ON CONFLICT (player_id)
DO UPDATE SET
	casual_mmr = EXCLUDED.casual_mmr,
	ranked_mmr = EXCLUDED.ranked_mmr,
	solo_rank_points = EXCLUDED.solo_rank_points,
	casual_matches_played = EXCLUDED.casual_matches_played,
	ranked_matches_played = EXCLUDED.ranked_matches_played,
	casual_matches_played_seasonal = EXCLUDED.casual_matches_played_seasonal,
	ranked_matches_played_seasonal = EXCLUDED.ranked_matches_played_seasonal,
	ranked_placement_matches = EXCLUDED.ranked_placement_matches,
	current_solo_rank = EXCLUDED.current_solo_rank,
	highest_team_rank = EXCLUDED.highest_team_rank,
	casual_matches_won = EXCLUDED.casual_matches_won,
	ranked_matches_won = EXCLUDED.ranked_matches_won,
	priority_matchmaking_until = EXCLUDED.priority_matchmaking_until,
	restrict_matchmaking_until = EXCLUDED.restrict_matchmaking_until,
	map_history = EXCLUDED.map_history;