INSERT INTO player_config (
	player_id,
    unlock_all_play_modes,
    unlock_all_menu_tabs,
    unlock_all_sponsors,
    bypass_unlock_all_sponsors_override,
    bypass_progression_overrides,
    bypass_team_size_overrides,
    bypass_region_select_override,
    bypass_currency_purchasing_override,
    disable_dev_map_selector,
    show_debug_info_panel,
    show_platform_info_panel,
    show_matchmaking_counters,
    force_chat_enabled,
    most_recent_lobby_mode,
    most_recent_party_id,
    eula_accepted_version,
    eula_accepted_version_playstation,
    eula_accepted_version_xbox,
    tos_accepted_version,
    tos_accepted_version_playstation,
    tos_accepted_version_xbox,
    nda_accepted_version,
    nda_accepted_version_playstation,
    nda_accepted_version_xbox,
    seizure_warning_ack_version,
    seizure_warning_ack_version_playstation,
    seizure_warning_ack_version_xbox,
    battlepass_season_logged_on,
    battlepass_purchase_popup_last_time,
    nda_signature,
    nda_signature_playstation,
    nda_signature_xbox,
    nda_email,
    nda_email_playstation,
    nda_email_xbox,
    last_version_shown_in_drivers_warning,
    min_spec_warning_times_displayed,
    ping_warning_dialog_times_displayed,
    completed_launch_settings_flow,
    using_manual_matchmaking_region_selection,
    manual_matchmaking_region_selections,
    rotating_news_viewed_messages,
    ink_quality,
    mouse_sensitivity_ads_scale,
    minimap_scale,
    minimap_size,
    minimap_mask_opacity,
    inverted_y_axis,
    toggle_crouch,
    toggle_walk,
    toggle_ads,
    recoil_behavior,
    left_handed_enabled,
    recoil_pitch_correction_enabled,
    is_team_laser_enabled,
    is_hud_minimap_rotation_enabled,
    is_hud_minimap_centered_on_player,
    is_hud_minimap_circle,
    is_hud_minimap_mask_high_contrast_enabled,
    is_hud_snap_minimap_with_scoreboard_enabled,
    is_damage_camera_effect_enabled,
    streamer_mode_enabled,
    hide_lobby_code,
    ads_tracer_ratio,
    ads_tracer_intensity,
    optic_hit_confirm_intensity,
    anonymous_mode,
    anonymize_player_names,
    streamer_mode_disable_incoming_voice_chat,
    streamer_mode_disable_incoming_text_chat,
    is_text_chat_sound_effects_enabled,
    subtitles_enabled,
    verbose_vo_level,
    is_blood_fx_enabled,
    override_keymaps,
    voice_chat_input_audio_device,
    voice_chat_output_audio_device,
    voice_chat_team_enabled,
    voice_chat_console_mode,
    voice_chat_party_enabled,
    voice_chat_party_enabled_in_game,
    voice_chat_team_push_to_talk,
    voice_chat_party_push_to_talk,
    enabled_text_stats,
    enabled_graph_stats,
    muted_chat_contexts,
    input_bindings_version,
    player_config_version
) VALUES (
    @player_id,
    @unlock_all_play_modes,
    @unlock_all_menu_tabs,
    @unlock_all_sponsors,
    @bypass_unlock_all_sponsors_override,
    @bypass_progression_overrides,
    @bypass_team_size_overrides,
    @bypass_region_select_override,
    @bypass_currency_purchasing_override,
    @disable_dev_map_selector,
    @show_debug_info_panel,
    @show_platform_info_panel,
    @show_matchmaking_counters,
    @force_chat_enabled,
    @most_recent_lobby_mode,
    @most_recent_party_id,
    @eula_accepted_version,
    @eula_accepted_version_playstation,
    @eula_accepted_version_xbox,
    @tos_accepted_version,
    @tos_accepted_version_playstation,
    @tos_accepted_version_xbox,
    @nda_accepted_version,
    @nda_accepted_version_playstation,
    @nda_accepted_version_xbox,
    @seizure_warning_ack_version,
    @seizure_warning_ack_version_playstation,
    @seizure_warning_ack_version_xbox,
    @battlepass_season_logged_on,
    @battlepass_purchase_popup_last_time,
    @nda_signature,
    @nda_signature_playstation,
    @nda_signature_xbox,
    @nda_email,
    @nda_email_playstation,
    @nda_email_xbox,
    @last_version_shown_in_drivers_warning,
    @min_spec_warning_times_displayed,
    @ping_warning_dialog_times_displayed,
    @completed_launch_settings_flow,
    @using_manual_matchmaking_region_selection,
    @manual_matchmaking_region_selections,
    @rotating_news_viewed_messages,
    @ink_quality,
    @mouse_sensitivity_ads_scale,
    @minimap_scale,
    @minimap_size,
    @minimap_mask_opacity,
    @inverted_y_axis,
    @toggle_crouch,
    @toggle_walk,
    @toggle_ads,
    @recoil_behavior,
    @left_handed_enabled,
    @recoil_pitch_correction_enabled,
    @is_team_laser_enabled,
    @is_hud_minimap_rotation_enabled,
    @is_hud_minimap_centered_on_player,
    @is_hud_minimap_circle,
    @is_hud_minimap_mask_high_contrast_enabled,
    @is_hud_snap_minimap_with_scoreboard_enabled,
    @is_damage_camera_effect_enabled,
    @streamer_mode_enabled,
    @hide_lobby_code,
    @ads_tracer_ratio,
    @ads_tracer_intensity,
    @optic_hit_confirm_intensity,
    @anonymous_mode,
    @anonymize_player_names,
    @streamer_mode_disable_incoming_voice_chat,
    @streamer_mode_disable_incoming_text_chat,
    @is_text_chat_sound_effects_enabled,
    @subtitles_enabled,
    @verbose_vo_level,
    @is_blood_fx_enabled,
    @override_keymaps,
    @voice_chat_input_audio_device,
    @voice_chat_output_audio_device,
    @voice_chat_team_enabled,
    @voice_chat_console_mode,
    @voice_chat_party_enabled,
    @voice_chat_party_enabled_in_game,
    @voice_chat_team_push_to_talk,
    @voice_chat_party_push_to_talk,
    @enabled_text_stats,
    @enabled_graph_stats,
    @muted_chat_contexts,
    @input_bindings_version,
    @player_config_version
) ON CONFLICT (player_id)
DO UPDATE SET
    player_id = EXCLUDED.player_id,
    unlock_all_play_modes = EXCLUDED.unlock_all_play_modes,
    unlock_all_menu_tabs = EXCLUDED.unlock_all_menu_tabs,
    unlock_all_sponsors = EXCLUDED.unlock_all_sponsors,
    bypass_unlock_all_sponsors_override = EXCLUDED.bypass_unlock_all_sponsors_override,
    bypass_progression_overrides = EXCLUDED.bypass_progression_overrides,
    bypass_team_size_overrides = EXCLUDED.bypass_team_size_overrides,
    bypass_region_select_override = EXCLUDED.bypass_region_select_override,
    bypass_currency_purchasing_override = EXCLUDED.bypass_currency_purchasing_override,
    disable_dev_map_selector = EXCLUDED.disable_dev_map_selector,
    show_debug_info_panel = EXCLUDED.show_debug_info_panel,
    show_platform_info_panel = EXCLUDED.show_platform_info_panel,
    show_matchmaking_counters = EXCLUDED.show_matchmaking_counters,
    force_chat_enabled = EXCLUDED.force_chat_enabled,
    most_recent_lobby_mode = EXCLUDED.most_recent_lobby_mode,
    most_recent_party_id = EXCLUDED.most_recent_party_id,
    eula_accepted_version = EXCLUDED.eula_accepted_version,
    eula_accepted_version_playstation = EXCLUDED.eula_accepted_version_playstation,
    eula_accepted_version_xbox = EXCLUDED.eula_accepted_version_xbox,
    tos_accepted_version = EXCLUDED.tos_accepted_version,
    tos_accepted_version_playstation = EXCLUDED.tos_accepted_version_playstation,
    tos_accepted_version_xbox = EXCLUDED.tos_accepted_version_xbox,
    nda_accepted_version = EXCLUDED.nda_accepted_version,
    nda_accepted_version_playstation = EXCLUDED.nda_accepted_version_playstation,
    nda_accepted_version_xbox = EXCLUDED.nda_accepted_version_xbox,
    seizure_warning_ack_version = EXCLUDED.seizure_warning_ack_version,
    seizure_warning_ack_version_playstation = EXCLUDED.seizure_warning_ack_version_playstation,
    seizure_warning_ack_version_xbox = EXCLUDED.seizure_warning_ack_version_xbox,
    battlepass_season_logged_on = EXCLUDED.battlepass_season_logged_on,
    battlepass_purchase_popup_last_time = EXCLUDED.battlepass_purchase_popup_last_time,
    nda_signature = EXCLUDED.nda_signature,
    nda_signature_playstation = EXCLUDED.nda_signature_playstation,
    nda_signature_xbox = EXCLUDED.nda_signature_xbox,
    nda_email = EXCLUDED.nda_email,
    nda_email_playstation = EXCLUDED.nda_email_playstation,
    nda_email_xbox = EXCLUDED.nda_email_xbox,
    last_version_shown_in_drivers_warning = EXCLUDED.last_version_shown_in_drivers_warning,
    min_spec_warning_times_displayed = EXCLUDED.min_spec_warning_times_displayed,
    ping_warning_dialog_times_displayed = EXCLUDED.ping_warning_dialog_times_displayed,
    completed_launch_settings_flow = EXCLUDED.completed_launch_settings_flow,
    using_manual_matchmaking_region_selection = EXCLUDED.using_manual_matchmaking_region_selection,
    manual_matchmaking_region_selections = EXCLUDED.manual_matchmaking_region_selections,
    rotating_news_viewed_messages = EXCLUDED.rotating_news_viewed_messages,
    ink_quality = EXCLUDED.ink_quality,
    mouse_sensitivity_ads_scale = EXCLUDED.mouse_sensitivity_ads_scale,
    minimap_scale = EXCLUDED.minimap_scale,
    minimap_size = EXCLUDED.minimap_size,
    minimap_mask_opacity = EXCLUDED.minimap_mask_opacity,
    inverted_y_axis = EXCLUDED.inverted_y_axis,
    toggle_crouch = EXCLUDED.toggle_crouch,
    toggle_walk = EXCLUDED.toggle_walk,
    toggle_ads = EXCLUDED.toggle_ads,
    recoil_behavior = EXCLUDED.recoil_behavior,
    left_handed_enabled = EXCLUDED.left_handed_enabled,
    recoil_pitch_correction_enabled = EXCLUDED.recoil_pitch_correction_enabled,
    is_team_laser_enabled = EXCLUDED.is_team_laser_enabled,
    is_hud_minimap_rotation_enabled = EXCLUDED.is_hud_minimap_rotation_enabled,
    is_hud_minimap_centered_on_player = EXCLUDED.is_hud_minimap_centered_on_player,
    is_hud_minimap_circle = EXCLUDED.is_hud_minimap_circle,
    is_hud_minimap_mask_high_contrast_enabled = EXCLUDED.is_hud_minimap_mask_high_contrast_enabled,
    is_hud_snap_minimap_with_scoreboard_enabled = EXCLUDED.is_hud_snap_minimap_with_scoreboard_enabled,
    is_damage_camera_effect_enabled = EXCLUDED.is_damage_camera_effect_enabled,
    streamer_mode_enabled = EXCLUDED.streamer_mode_enabled,
    hide_lobby_code = EXCLUDED.hide_lobby_code,
    ads_tracer_ratio = EXCLUDED.ads_tracer_ratio,
    ads_tracer_intensity = EXCLUDED.ads_tracer_intensity,
    optic_hit_confirm_intensity = EXCLUDED.optic_hit_confirm_intensity,
    anonymous_mode = EXCLUDED.anonymous_mode,
    anonymize_player_names = EXCLUDED.anonymize_player_names,
    streamer_mode_disable_incoming_voice_chat = EXCLUDED.streamer_mode_disable_incoming_voice_chat,
    streamer_mode_disable_incoming_text_chat = EXCLUDED.streamer_mode_disable_incoming_text_chat,
    is_text_chat_sound_effects_enabled = EXCLUDED.is_text_chat_sound_effects_enabled,
    subtitles_enabled = EXCLUDED.subtitles_enabled,
    verbose_vo_level = EXCLUDED.verbose_vo_level,
    is_blood_fx_enabled = EXCLUDED.is_blood_fx_enabled,
    override_keymaps = EXCLUDED.override_keymaps,
    voice_chat_input_audio_device = EXCLUDED.voice_chat_input_audio_device,
    voice_chat_output_audio_device = EXCLUDED.voice_chat_output_audio_device,
    voice_chat_team_enabled = EXCLUDED.voice_chat_team_enabled,
    voice_chat_console_mode = EXCLUDED.voice_chat_console_mode,
    voice_chat_party_enabled = EXCLUDED.voice_chat_party_enabled,
    voice_chat_party_enabled_in_game = EXCLUDED.voice_chat_party_enabled_in_game,
    voice_chat_team_push_to_talk = EXCLUDED.voice_chat_team_push_to_talk,
    voice_chat_party_push_to_talk = EXCLUDED.voice_chat_party_push_to_talk,
    enabled_text_stats = EXCLUDED.enabled_text_stats,
    enabled_graph_stats = EXCLUDED.enabled_graph_stats,
    muted_chat_contexts = EXCLUDED.muted_chat_contexts,
    input_bindings_version = EXCLUDED.input_bindings_version,
    player_config_version = EXCLUDED.player_config_version;