INSERT INTO match_history_player_data (
	match_id,
	team_number,
	player_id,
	native_platform_id,
	saved_player_name,
	selected_banner_catalog_id,
	saved_sponsor_name,
	sponsor_game_id,
	is_anonymous_player,
	has_crew_score_earned,
	teammate_index,
	num_kills,
	num_assists,
	num_deaths,
	total_damage,
	current_rank_id,
	previous_rank_id,
	current_ranked_rating,
	previous_ranked_rating,
	ranked_rating_delta,
	crew_score,
	crew_id,
	division_id,
	division_type,
	match_placement_data,
	num_ranked_matches
) VALUES (
	@match_id,
	@team_number,
	@player_id,
	@native_platform_id,
	@saved_player_name,
	@selected_banner_catalog_id,
	@saved_sponsor_name,
	@sponsor_game_id,
	@is_anonymous_player,
	@has_crew_score_earned,
	@teammate_index,
	@num_kills,
	@num_assists,
	@num_deaths,
	@total_damage,
	@current_rank_id,
	@previous_rank_id,
	@current_ranked_rating,
	@previous_ranked_rating,
	@ranked_rating_delta,
	@crew_score,
	@crew_id,
	@division_id,
	@division_type,
	@match_placement_data,
	@num_ranked_matches
) ON CONFLICT (match_id, team_number, player_id) DO UPDATE SET
	native_platform_id = EXCLUDED.native_platform_id,
	saved_player_name = EXCLUDED.saved_player_name,
	selected_banner_catalog_id = EXCLUDED.selected_banner_catalog_id,
	saved_sponsor_name = EXCLUDED.saved_sponsor_name,
	sponsor_game_id = EXCLUDED.sponsor_game_id,
	is_anonymous_player = EXCLUDED.is_anonymous_player,
	has_crew_score_earned = EXCLUDED.has_crew_score_earned,
	teammate_index = EXCLUDED.teammate_index,
	num_kills = EXCLUDED.num_kills,
	num_assists = EXCLUDED.num_assists,
	num_deaths = EXCLUDED.num_deaths,
	total_damage = EXCLUDED.total_damage,
	current_rank_id = EXCLUDED.current_rank_id,
	previous_rank_id = EXCLUDED.previous_rank_id,
	current_ranked_rating = EXCLUDED.current_ranked_rating,
	previous_ranked_rating = EXCLUDED.previous_ranked_rating,
	ranked_rating_delta = EXCLUDED.ranked_rating_delta,
	crew_score = EXCLUDED.crew_score,
	crew_id = EXCLUDED.crew_id,
	division_id = EXCLUDED.division_id,
	division_type = EXCLUDED.division_type,
	match_placement_data = EXCLUDED.match_placement_data,
	num_ranked_matches = EXCLUDED.num_ranked_matches;