INSERT INTO parties (
	party_id,
	members,
	invite_code,
	queue_pool,
	lobby_mode,
	chat_id,
	use_team_mmr,
	party_version,
	party_ext_version,
	region,
	tag,
	profile,
	has_acceptable_region,
	preferred_game_server_zones,
	standard,
	custom_json,
	crossplay_platform
) VALUES (
	@party_id,
	@members,
	@invite_code,
	@queue_pool,
	@lobby_mode,
	@chat_id,
	@use_team_mmr,
	@version,
	@party_ext_version,
	@region,
	@tag,
	@profile,
	@has_acceptable_region,
	@preferred_game_server_zones,
	@standard,
	@custom_json,
	@crossplay_platform
) ON CONFLICT (party_id)
DO UPDATE SET
	members = EXCLUDED.members,
	invite_code = EXCLUDED.invite_code,
	queue_pool = EXCLUDED.queue_pool,
	lobby_mode = EXCLUDED.lobby_mode,
	chat_id = EXCLUDED.chat_id,
	use_team_mmr = EXCLUDED.use_team_mmr,
	party_version = EXCLUDED.party_version,
	party_ext_version = EXCLUDED.party_ext_version,
	region = EXCLUDED.region,
	tag = EXCLUDED.tag,
	profile = EXCLUDED.profile,
	has_acceptable_region = EXCLUDED.has_acceptable_region,
	preferred_game_server_zones = EXCLUDED.preferred_game_server_zones,
	standard = EXCLUDED.standard,
	custom_json = EXCLUDED.custom_json,
	crossplay_platform = EXCLUDED.crossplay_platform;