INSERT INTO match_history_team_data (
	match_id,
	team_number,
	rounds_played,
	rounds_won,
	xp_per_round,
	xp_per_round_won,
	team_id,
	current_rank_id,
	previous_rank_id,
	current_ranked_rating,
	previous_ranked_rating,
	ranked_rating_delta,
	match_placement_data,
	num_ranked_matches,
	fans_per_round,
	fans_per_round_won,
	used_team_rank,
	is_full_team_in_party
) VALUES (
	@match_id,
	@team_number,
	@rounds_played,
	@rounds_won,
	@xp_per_round,
	@xp_per_round_won,
	@team_id,
	@current_rank_id,
	@previous_rank_id,
	@current_ranked_rating,
	@previous_ranked_rating,
	@ranked_rating_delta,
	@match_placement_data,
	@num_ranked_matches,
	@fans_per_round,
	@fans_per_round_won,
	@used_team_rank,
	@is_full_team_in_party
) ON CONFLICT (match_id, team_number) DO UPDATE SET
	rounds_played = EXCLUDED.rounds_played,
	rounds_won = EXCLUDED.rounds_won,
	xp_per_round = EXCLUDED.xp_per_round,
	xp_per_round_won = EXCLUDED.xp_per_round_won,
	team_id = EXCLUDED.team_id,
	current_rank_id = EXCLUDED.current_rank_id,
	previous_rank_id = EXCLUDED.previous_rank_id,
	current_ranked_rating = EXCLUDED.current_ranked_rating,
	previous_ranked_rating = EXCLUDED.previous_ranked_rating,
	ranked_rating_delta = EXCLUDED.ranked_rating_delta,
	match_placement_data = EXCLUDED.match_placement_data,
	num_ranked_matches = EXCLUDED.num_ranked_matches,
	fans_per_round = EXCLUDED.fans_per_round,
	fans_per_round_won = EXCLUDED.fans_per_round_won,
	used_team_rank = EXCLUDED.used_team_rank,
	is_full_team_in_party = EXCLUDED.is_full_team_in_party;